# Use the official .NET 8.0 SDK image as a base
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Install any additional dependencies here
# RUN apt-get update && apt-get install -y <your-packages>

# Set the working directory
WORKDIR /workspaces/DSAPractice
